name: Deploy to Firebase
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Navigate to frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build
          
      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        working-directory: ./frontend
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}